/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { News } from "./News";
import { NewsCountArgs } from "./NewsCountArgs";
import { NewsFindManyArgs } from "./NewsFindManyArgs";
import { NewsFindUniqueArgs } from "./NewsFindUniqueArgs";
import { DeleteNewsArgs } from "./DeleteNewsArgs";
import { NewsService } from "../news.service";
@graphql.Resolver(() => News)
export class NewsResolverBase {
  constructor(protected readonly service: NewsService) {}

  async _newsItemsMeta(
    @graphql.Args() args: NewsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [News])
  async newsItems(@graphql.Args() args: NewsFindManyArgs): Promise<News[]> {
    return this.service.newsItems(args);
  }

  @graphql.Query(() => News, { nullable: true })
  async news(@graphql.Args() args: NewsFindUniqueArgs): Promise<News | null> {
    const result = await this.service.news(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => News)
  async deleteNews(@graphql.Args() args: DeleteNewsArgs): Promise<News | null> {
    try {
      return await this.service.deleteNews(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
