/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Workflow } from "./Workflow";
import { WorkflowCountArgs } from "./WorkflowCountArgs";
import { WorkflowFindManyArgs } from "./WorkflowFindManyArgs";
import { WorkflowFindUniqueArgs } from "./WorkflowFindUniqueArgs";
import { DeleteWorkflowArgs } from "./DeleteWorkflowArgs";
import { WorkflowService } from "../workflow.service";
@graphql.Resolver(() => Workflow)
export class WorkflowResolverBase {
  constructor(protected readonly service: WorkflowService) {}

  async _workflowsMeta(
    @graphql.Args() args: WorkflowCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Workflow])
  async workflows(
    @graphql.Args() args: WorkflowFindManyArgs
  ): Promise<Workflow[]> {
    return this.service.workflows(args);
  }

  @graphql.Query(() => Workflow, { nullable: true })
  async workflow(
    @graphql.Args() args: WorkflowFindUniqueArgs
  ): Promise<Workflow | null> {
    const result = await this.service.workflow(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Workflow)
  async deleteWorkflow(
    @graphql.Args() args: DeleteWorkflowArgs
  ): Promise<Workflow | null> {
    try {
      return await this.service.deleteWorkflow(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
