/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserInteraction } from "./UserInteraction";
import { UserInteractionCountArgs } from "./UserInteractionCountArgs";
import { UserInteractionFindManyArgs } from "./UserInteractionFindManyArgs";
import { UserInteractionFindUniqueArgs } from "./UserInteractionFindUniqueArgs";
import { DeleteUserInteractionArgs } from "./DeleteUserInteractionArgs";
import { UserInteractionService } from "../userInteraction.service";
@graphql.Resolver(() => UserInteraction)
export class UserInteractionResolverBase {
  constructor(protected readonly service: UserInteractionService) {}

  async _userInteractionsMeta(
    @graphql.Args() args: UserInteractionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserInteraction])
  async userInteractions(
    @graphql.Args() args: UserInteractionFindManyArgs
  ): Promise<UserInteraction[]> {
    return this.service.userInteractions(args);
  }

  @graphql.Query(() => UserInteraction, { nullable: true })
  async userInteraction(
    @graphql.Args() args: UserInteractionFindUniqueArgs
  ): Promise<UserInteraction | null> {
    const result = await this.service.userInteraction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserInteraction)
  async deleteUserInteraction(
    @graphql.Args() args: DeleteUserInteractionArgs
  ): Promise<UserInteraction | null> {
    try {
      return await this.service.deleteUserInteraction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
